name: Create Issue from Form

on:
  repository_dispatch:
    types: [create_issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            const { version, content } = context.payload.client_payload;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `新建议：${version}`,
              body: `版本：${version}\n\n${content}`,
              labels: ['suggestion']
            }); 